AutoStore.WEB/Controllers/AutoDetailController.cs
using AutoMapper;
using AutoStore.BLL.DTO;
using AutoStore.BLL.Infrastructure;
using AutoStore.BLL.Interfaces;
using AutoStore.WEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutoStore.WEB.Controllers
{
    public class AutoDetailController : Controller
    {

        private IService service;

        public AutoDetailController(IService service)
        {
            this.service = service;
        }
        // GET: AutoDetail
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            var cur_user = service.GetCurrentUser();
            if (cur_user != null)
            {
                return View();
            }
            else
                return RedirectToAction("Login", "Account");
        }


        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Create(AutoDetailViewModel detail)
        {
            var cur_user = service.GetCurrentUser();
            if (cur_user != null)
            {
                if (ModelState.IsValid)
                {
                    //Mapper.Reset();
                    //Mapper.Initialize(cfg => cfg.CreateMap<AutoDetailViewModel, AutoDetailDTO>());
                    var _detail = Mapper.Map<AutoDetailViewModel, AutoDetailDTO>(detail);
                    var result = service.CreateDetail(_detail);
                    return RedirectToAction("Index", "Home");
                }
                else
                    return View(detail);
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        [Authorize(Roles = "admin")]
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            var cur_user = service.GetCurrentUser();
            if (cur_user != null)
            {
                if (id != null)
                {
                    var _detailDTO = service.GetAutoDetail(id.Value);
                    //Mapper.Reset();
                    //Mapper.Initialize(cfg => cfg.CreateMap<AutoDetailDTO, AutoDetailViewModel>());
                    var _detail = Mapper.Map<AutoDetailDTO, AutoDetailViewModel>(_detailDTO);
                    if (_detail != null)
                        return View(_detail);
                    else
                        return RedirectToAction("Index", "Home");
                }
                else
                    return RedirectToAction("Index", "Home");
            }
            else
                return RedirectToAction("Login", "Account");
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Edit(AutoDetailViewModel detailViewModel)
        {
            var cur_user = service.GetCurrentUser();
            OperationDetails result;
            if (cur_user != null)
            {
                if (ModelState.IsValid)
                {
                    //Mapper.Reset();
                    //Mapper.Initialize(cfg => cfg.CreateMap<AutoDetailViewModel, AutoDetailDTO>());
                    var _detail = Mapper.Map<AutoDetailViewModel, AutoDetailDTO>(detailViewModel);
                    result = service.EditDetail(_detail);
                    if (result.Succedeed)
                        return RedirectToAction("Index", "Home");
                    else
                        return View(detailViewModel);
                }
                else
                    return View(detailViewModel);
            }
            else
                return RedirectToAction("Login", "Account");
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Delete(int? id)
        {
            if (service.GetCurrentUser() != null)
            {
                if (id != null)
                {
                    service.DeleteDetail(id.Value);
                }
                return RedirectToAction("Index", "Home");
            }
            else
                return RedirectToAction("Login", "Account");     
        }

        public ActionResult Details(int id)
        {
            var _detail = service.GetAutoDetails().FirstOrDefault(c => c.Id == id);
            if (_detail != null)
            {
                return PartialView(_detail);
            }
            return View();
        }
    }
}

AutoStore.WEB/Controllers/HomeController.cs
using AutoMapper;
using AutoStore.BLL.DTO;
using AutoStore.BLL.Interfaces;
using AutoStore.WEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutoStore.WEB.Controllers
{
    public class HomeController : Controller
    {
        IService service;

        public HomeController(IService serv)
        {
            service = serv;
            //service.CreateDetail(new AutoDetailDTO
            //{
            //    Article = "9333029",
            //    Name = "Ступицы колес",
            //    Brend = "Tech-as",
            //    Price = 124.5
            //}

        }


        public ActionResult Index()
        {
            IEnumerable<AutoDetailDTO> autoDetails = service.GetAutoDetails();
            //Mapper.Reset();
            //Mapper.Initialize(cfg => cfg.CreateMap<AutoDetailDTO, AutoDetailViewModel>());
            var details = Mapper.Map <IEnumerable<AutoDetailDTO>,  List<AutoDetailViewModel>>(autoDetails);
            return View(details);
        }

        public ActionResult DetailSearch(string name)
        {
            try
            {
                if (!name.Equals(""))
                {
                    var _details = service.GetAutoDetails().Where(a => a.Article.Contains(name)).ToList();
                    //Mapper.Reset();
                    //Mapper.Initialize(cfg => cfg.CreateMap<AutoDetailDTO, AutoDetailViewModel>());
                    var details = Mapper.Map<IEnumerable<AutoDetailDTO>, List<AutoDetailViewModel>>(_details);
                    return PartialView(details);
                }
                return PartialView();
            }catch(Exception e)
            {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

AutoStore.WEB/Controllers/OrderController.cs
using AutoMapper;
using AutoStore.BLL.DTO;
using AutoStore.BLL.Infrastructure;
using AutoStore.BLL.Interfaces;
using AutoStore.WEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutoStore.WEB.Controllers
{
    public class OrderController : Controller
    {
        IService service;
        private static NLog.Logger logger = NLog.LogManager.GetCurrentClassLogger();

        public OrderController(IService serv)
        {
            service = serv;
        }

        public ActionResult Index()
        {
            var orderDtos = service.GetOrders();
            //Mapper.Reset();
            //Mapper.Initialize(cfg => cfg.CreateMap<OrderDTO, OrderViewModel>());
            var orders = Mapper.Map<IEnumerable<OrderDTO>, List<OrderViewModel>>(orderDtos);
            return View(orders);
        }

        [HttpPost]
        public ActionResult Delete(int? id)
        {
            var cur_user = service.GetCurrentUser();
            OperationDetails result;
            if (cur_user != null)
            {
                if (id != null)
                {
                    result = service.DeleteOrder(id.Value);
                    logger.Info(result.Message);
                    return Redirect(Request.UrlReferrer.ToString());
                }
                else
                {
                    return Redirect(Request.UrlReferrer.ToString());
                }
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        [Authorize]
        public ActionResult Buy(int id)
        {
            var cur_user = service.GetCurrentUser();
            var order = new OrderDTO
            {
                Id = id,
                ClientProfileId = cur_user.IdUser,
                Date = DateTime.Now,
                Sum = service.GetAutoDetails().FirstOrDefault(c => c.Id == id).Price
            };
            OperationDetails result = service.MakeOrder(order);
            logger.Info(result.Message);
            return RedirectToAction("Index", "Home");
        }

    }
}

AutoStore.WEB/Views/Home/DetailSearch.cshtml
@model IEnumerable<AutoStore.WEB.Models.AutoDetailViewModel>


<div id="searchresults">
    @if (Model != null && Model.Count() > 0)
    {
        <h3>Результаты поиска</h3>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Article)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Brend)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th></th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Article)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Brend)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.ActionLink("Подробнее", "../AutoDetail/Details", new { id = item.Id }, new { @class = "info" })
                        @using (Html.BeginForm("Buy", "Order", FormMethod.Post, new { }))
                        {
                            <input type="hidden" value="@item.Id" name="id" />
                            <input type="submit" value="Buy" class="btn btn-link" />
                        }
                    </td>
                </tr>
            }
        </table>
    }
    else
    {
        <h3>Нет результатов</h3>
    }
</div>

AutoStore.WEB/Views/Home/Index.cshtml
@model IEnumerable<AutoStore.WEB.Models.AutoDetailViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>

<div class="row">
    <div class="col-md-2">Введите артикль</div>
    <div class="col-md-3 col-md-    -1">
        <input type="text" name="name" id="search" />
        <input type='button' id="submit" value='Поиск' />
    </div>
   
</div>
<div id="results"></div>

<br />
<table id="table-a" class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Article)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Article)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Подробнее", "../AutoDetail/Details", new { id = item.Id }, new { @class = "info" })
            </td>
            <td>
                @using (Html.BeginForm("Buy", "Order", FormMethod.Post, new { }))
                {
                    <input type="hidden" value="@item.Id" name="id" />
                    <input type="submit" value="Buy" class="btn btn-link" />
                }
            </td>
            <td>
                @if (User.IsInRole("admin"))
                {
                    using (Html.BeginForm("Delete", "AutoDetail", FormMethod.Post))
                    {
                        <input type="hidden" value="@item.Id" name="id" />
                        <input type="submit" value="Delete" class="btn btn-link" />
                    }
                    using (Html.BeginForm("Edit", "AutoDetail", FormMethod.Get))
                    {
                        <input type="hidden" value="@item.Id" name="id" />
                        <input type="submit" value="Edit" class="btn btn-link" />
                    }
                }
            </td>
        </tr>
    }
</table>


@section scripts{
    <script>
        $(function () {
            $.ajaxSetup({ cache: false });
            $(".info").click(function (e) {
                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })
    </script>
}

<script type="text/javascript">
    $(document).ready(function () {
        $('#submit').click(function (e) {
            e.preventDefault();
            var name = $('#search').val();
            name=encodeURIComponent(name);
            $('#results').load('@Url.Action("DetailSearch", "Home")?name=' + name);
            $('#table-a').hide();
        });
    });
</script>